# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-21 07:05
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EventType', models.CharField(choices=[(b'Exotica', b'Exotica'), (b'Techtix', b'Techtix')], default=b'Exotica', max_length=20)),
                ('EventName', models.CharField(max_length=200)),
                ('EventImage', stdimage.models.StdImageField(blank=True, upload_to=b'event/event_image')),
                ('NumberParticipants', models.DecimalField(decimal_places=0, max_digits=2)),
                ('tagline', models.TextField(default=b'Tagline here', null=True)),
                ('EventDetails', models.TextField(null=True)),
                ('EventDate', models.DateField()),
                ('StartTime', models.TimeField(null=True)),
                ('EndTime', models.TimeField(null=True)),
                ('key', models.CharField(max_length=2)),
                ('Participants', models.ManyToManyField(blank=True, related_name='events_registered', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event_Coordinator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CoordinatorName', models.CharField(max_length=200)),
                ('CoordinatorImage', stdimage.models.StdImageField(upload_to=b'event/coordinator_image')),
                ('CoordinatorEmail', models.EmailField(max_length=254)),
                ('CoordinatorPhone', models.CharField(default=1234567890, max_length=10, validators=[django.core.validators.RegexValidator(code=b'invalid_phonenumber', message=b'Please enter a valid phone number WITHOUT any PREFIX', regex=b'^[789]\\d{9}$')])),
                ('CoordinatorEvent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
            ],
        ),
    ]
