# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-19 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20170123_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='NumberParticipants',
            field=models.DecimalField(decimal_places=0, default=3, max_digits=2),
            preserve_default=False,
        ),
    ]
