# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-19 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='accomodation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='phone_no',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
