# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-27 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='secretkey',
        ),
        migrations.AddField(
            model_name='team',
            name='number_of_members',
            field=models.DecimalField(decimal_places=0, default=6, max_digits=1),
        ),
        migrations.AddField(
            model_name='team',
            name='secret_key',
            field=models.CharField(default=6, max_length=20),
            preserve_default=False,
        ),
    ]
