# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-19 11:46
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0003_auto_20170219_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='phone_no',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(code='invalid_phonenumber', message='Please enter a valid phone number WITHOUT any PREFIX', regex='^[789]\\d{9}$')]),
        ),
    ]
