# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-23 11:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20170123_1057'),
        ('profile', '0003_auto_20161227_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='event',
            field=models.ManyToManyField(to='events.Event'),
        ),
        migrations.AlterField(
            model_name='team',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event'),
        ),
    ]
