# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-23 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0004_auto_20170123_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='event',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
