# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-19 12:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0005_auto_20170219_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='department',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='year',
        ),
    ]
