# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-23 13:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0006_auto_20170123_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='event',
        ),
    ]
