# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-23 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30)),
                ('college_Name', models.CharField(max_length=50)),
                ('college_Address', models.CharField(max_length=20)),
                ('Email_Address', models.EmailField(max_length=254)),
                ('facebook_Link', models.URLField(blank=True, null=True)),
                ('innitaitives', models.TextField()),
            ],
        ),
    ]
