# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-26 20:10
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusambassador', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='PhoneNo',
            field=models.CharField(default=1234567890, max_length=10, validators=[django.core.validators.RegexValidator(code=b'invalid_phonenumber', message=b'Please enter a valid phone number WITHOUT any PREFIX', regex=b'^[789]\\d{9}$')]),
        ),
    ]
