# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-18 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusambassador', '0002_signup_phoneno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='college_Address',
        ),
        migrations.AddField(
            model_name='signup',
            name='gender',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
