# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-18 15:43
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusambassador', '0003_auto_20170218_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='innitaitives',
        ),
        migrations.AlterField(
            model_name='signup',
            name='PhoneNo',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(code=b'invalid_phonenumber', message=b'Please enter a valid phone number WITHOUT any PREFIX', regex=b'^[789]\\d{9}$')]),
        ),
    ]
